version: "3"
services:
  app:
    container_name: notification-service
    restart: always
    build:
      context: ./
      args:
        port: "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
